# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 陈鑫磊的博客
subtitle: ''
description: '没有BUG的代码是不完美的'
keywords: 
  - 陈鑫磊的博客
  - cxl2020MC
  - cxl2020MC`s blog
  - cxl
author: 陈鑫磊
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.cxl2020mc.top
# permalink: :year/:month/:day/:title/
permalink: post/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
    - config.yaml

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
# updated_option: 'mtime'
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  # type: git
  # repo:
    # GithubToken放环境变量里了
    # gitHub: https://cxl2020MC:${{ secrets.GITHUBTOKEN }}@github.com/cxl2020MC/blog.git
    # gitee: https://[GiteeUsername]:[GiteeToken]@gitee.com/[GiteeUsername]/[GiteeBlogRepo].git[,branch]
    # coding: https://[TokenUser]:[CodingToken]@e.coding.net/[CodingUsername]/[CodingBlogRepo].git[,branch]
  # [,branch]为可选项，表示部署的分支
  #2020年10月后github新建仓库默认分支改为main
  # type: cos
  # 放环境变量里了

# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # 开关
  priority: 5 #过滤器优先权
  issues: false #issues标签依赖注入开关
  link:
    placeholder: /img/link.png # /img/link.png #link_card标签默认的图标图片
  CDN:
    #动画标签anima的依赖
    anima: https://jsd.cxl2020mc.top/npm/hexo-butterfly-tag-plugins-plus@latest/lib/assets/font-awesome-animation.min.css
    #issues标签依赖
    jquery: https://jsd.cxl2020mc.top/npm/jquery@latest/dist/jquery.min.js
    #issues标签依赖
    issues: https://jsd.cxl2020mc.top/npm/hexo-butterfly-tag-plugins-plus@latest/lib/assets/issues.js
    # iconfont标签symbol样式引入，如果不想引入，则设为false
    # //at.alicdn.com/t/font_2032782_8d5kxvn09md.js
    # 参看https://akilar.top/posts/d2ebecef/
    # https://cxl2020mc-1304820025.file.myqcloud.com/js/font_2032782_8d5kxvn09md.js
    iconfont: false
    # carousel旋转相册标签鼠标拖动依赖，如果不想引入则设为false
    # https://jsd.cxl2020mc.top/npm/hexo-butterfly-tag-plugins-plus@latest/lib/assets/carousel-touch.js
    carousel: false
    # 外挂标签样式的CSS依赖
    tag_plugins_css: https://jsd.cxl2020mc.top/npm/hexo-butterfly-tag-plugins-plus@latest/lib/tag_plugins.css

search:
  path: search.json # search.xml
  field: all
  content: true

feed:
  enable: true
  # Generate both atom and rss2 feeds
  type:
    - atom
    - rss2
  path:
    - atom.xml
    - rss2.xml
  limit: 20
  hub:
  content: true
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: https://www.cxl2020mc.top/img/favicon.png
  autodiscovery: true
  template:

# HexoPlusPlus Talk
# see https://hexoplusplus.js.org
hpptalk:
  enable: true 
  domain: plusplus.cxl2020mc.workers.dev
  path:
  limit:
  start:
  js:
  css:
  option:
  front_matter:

sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  # template: ./sitemap_template.xml
  # template_txt: ./sitemap_template.txt
  rel: true
  tags: true
  categories: true


encrypt: # hexo-blog-encrypt
  abstract: 有东西被加密了, 请输入密码查看.
  message: 您好, 这里需要密码.
  # tags:
    # - {name: tagName, password: 密码A}
    # - {name: tagName, password: 密码B}
  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: false #开关插件版看板娘
  scriptFrom: https://jsd.cxl2020mc.top/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://jsd.cxl2020mc.top/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  dialog:
    enable: true # 显示对话框人物显示对话框
    # hitokoto: true # 启用 hitokoto 使用一言API
  model:
    use: https://cxl2020mc-1304820025.file.myqcloud.com/wives/snow_miku/model.json # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://jsd.cxl2020mc.top/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
  display:
    position: right #控制看板娘位置
    width: 300 #控制看板娘大小
    height: 300 #控制看板娘大小
    hOffset: 0
    vOffset: -20 # -20
  mobile:
    show: false # 手机中是否展示
    scale: 0.8 # 0.5

# envelope_comment
# see https://akilar.top/posts/e2d3c450/
envelope_comment:
  enable: true #控制开关
  custom_pic:      
    cover: https://jsd.cxl2020mc.top/npm/hexo-butterfly-envelope/lib/violet.jpg #信笺头部图片
    line: https://jsd.cxl2020mc.top/npm/hexo-butterfly-envelope/lib/line.png #信笺底部图片
    beforeimg: https://jsd.cxl2020mc.top/npm/hexo-butterfly-envelope/lib/before.png # 信封前半部分
    afterimg: https://jsd.cxl2020mc.top/npm/hexo-butterfly-envelope/lib/after.png # 信封后半部分
  message: #信笺正文，多行文本，写法如下
    - 有什么想问的？
    - 有什么想说的？
    - 有什么想吐槽的？
    - 哪怕是有什么想吃的，都可以告诉我哦~
  bottom: 自动书记人偶竭诚为您服务！ #仅支持单行文本
  height: #1050px，信封划出的高度
  path: messageboard #【可选】comments 的路径名称。默认为 comments，生成的页面为 comments/index.html
  front_matter: #【可选】comments页面的 front_matter 配置
    title: 留言板
    comments: true

# hexo-filter-gitcalendar
# see https://akilar.top/posts/1f9c68c9/
gitcalendar:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: / # 应用页面
  # butterfly挂载容器
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  # volantis挂载容器
  # layout:
  #   type: class
  #   name: l_main
  #   index: 0
  # matery挂载容器
  # layout:
  #   type: id
  #   name: indexCard
  #   index: 0
  # mengd挂载容器
  # layout:
  #   type: class
  #   name: content
  #   index: 0
  user: cxl2020MC #git用户名
  apiurl: 'https://gitcalendar.cxl2020mc.top'
  jsonurl: #开发者专用
  minheight:
    pc: 280px #桌面端最小高度
    mibile: 0px #移动端最小高度
  # color: "['#e4dfd7', '#f9f4dc', '#f7e8aa', '#f7e8aa', '#f8df72', '#fcd217', '#fcc515', '#f28e16', '#fb8b05', '#d85916', '#f43e06']" #橘黄色调
  # color: "['#ebedf0', '#fdcdec', '#fc9bd9', '#fa6ac5', '#f838b2', '#f5089f', '#c4067e', '#92055e', '#540336', '#48022f', '#30021f']" #浅紫色调
  color: "['#ebedf0', '#f0fff4', '#dcffe4', '#bef5cb', '#85e89d', '#34d058', '#28a745', '#22863a', '#176f2c', '#165c26', '#144620']" #翠绿色调
  # color: "['#ebedf0', '#f1f8ff', '#dbedff', '#c8e1ff', '#79b8ff', '#2188ff', '#0366d6', '#005cc5', '#044289', '#032f62', '#05264c']" #天青色调
  container: .recent-post-item(style='width:100%;height:auto;padding:10px;') #父元素容器，需要使用pug语法
  gitcalendar_css: https://jsd.cxl2020mc.top/npm/hexo-filter-gitcalendar/lib/gitcalendar.css
  gitcalendar_js: https://jsd.cxl2020mc.top/npm/hexo-filter-gitcalendar/lib/gitcalendar.js

# hexo-butterfly-swiper
# see https://akilar.top/posts/8e1264d1/
swiper:
  enable: false # 开关
  priority: 5 #过滤器优先权
  enable_page: / # 应用页面
  timemode: date #date/updated
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  swiper_css: https://jsd.cxl2020mc.top/npm/hexo-butterfly-swiper/lib/swiper.min.css #swiper css依赖
  swiper_js: https://jsd.cxl2020mc.top/npm/hexo-butterfly-swiper/lib/swiper.min.js #swiper js依赖
  custom_css: https://jsd.cxl2020mc.top/npm/hexo-butterfly-swiper/lib/swiperstyle.css # 适配主题样式补丁
  custom_js: https://jsd.cxl2020mc.top/npm/hexo-butterfly-swiper/lib/swiper_init.js # swiper初始化方法

# electric_clock
# see https://akilar.top/posts/4e39cf4a/
electric_clock:
  enable: false # 开关
  priority: 5 #过滤器优先权
  enable_page: all # 应用页面
  exclude:
     - /post/
     - /about/
  layout: # 挂载容器类型
    type: class
    name: sticky_layout
    index: 0
  loading: https://jsd.cxl2020mc.top/npm/hexo-butterfly-clock/lib/loading.gif #加载动画自定义
  clock_css: https://jsd.cxl2020mc.top/npm/hexo-butterfly-clock/lib/clock.min.css
  clock_js: https://jsd.cxl2020mc.top/npm/hexo-butterfly-clock/lib/clock.min.js
  ip_api: https://pv.sohu.com/cityjson?ie=utf-8


# hexo-offline-popup.
service_worker:
  maximumFileSizeToCacheInBytes: 15145728 # 缓存的最大文件大小，以字节为单位，此处设置为3MB。(3145728)
  staticFileGlobs:
    - public/**/*.{js,html,xml,css,png,jpg,gif,svg,webp,eot,ttf,woff,woff2}
    # - public/**/*.{html,xml} #精简版使用这行即可
  # 静态文件合集，如果你的站点使用了例如webp格式的文件，请将文件类型添加进去。。
  # 注意，此处的文件类型就是会缓存下来的所有文件类型，如果不需要缓存那么多，
  # 而只是想判断网页更新与否，缓存html和xml即可。
  stripPrefix: public
  verbose: false
  runtimeCaching:
    # CDNs - should be cacheFirst, since they should be used specific versions so should not change
    - urlPattern: /* # 如果你需要加载CDN資源，请配置该选项，如果沒有，可以不配置。
      handler: cacheFirst
      options:
        origin: unpkg.com # unpkg
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.jsdelivr.net # jsdelivr
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: jsd.cxl2020mc.top
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cxl2020mc-1304820025.file.myqcloud.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: api.cxl2020mc.top
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cn.bing.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: gravatar.cxl2020mc.top # 头像
        
    # 更多cdn可自行参照上述格式进行配置。